object FormTemplate: TFormTemplate
  Left = 0
  Top = 0
  Align = alClient
  BorderStyle = bsNone
  Caption = 'FormTemplate'
  ClientHeight = 623
  ClientWidth = 1106
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 115
  TextHeight = 16
  object pnlMain: TPanel
    Left = 0
    Top = 0
    Width = 1106
    Height = 623
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 0
    object pnlTop: TPanel
      Left = 0
      Top = 0
      Width = 1106
      Height = 141
      Align = alTop
      BevelOuter = bvNone
      Padding.Left = 200
      Padding.Top = 30
      Padding.Right = 200
      ParentBackground = False
      TabOrder = 0
      object pnlCabecalho: TPanel
        Left = 200
        Top = 30
        Width = 193
        Height = 111
        Align = alLeft
        BevelOuter = bvNone
        TabOrder = 0
        object lblNomePagina: TLabel
          Left = 0
          Top = 0
          Width = 193
          Height = 16
          Align = alTop
          Caption = 'Nome da p'#225'gina'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 93
        end
        object pnlLinhaNomePagina: TPanel
          Left = 0
          Top = 16
          Width = 193
          Height = 2
          Align = alTop
          TabOrder = 0
        end
        object pnlBodyBotao: TPanel
          Left = 0
          Top = 18
          Width = 193
          Height = 93
          Align = alClient
          BevelOuter = bvNone
          ParentBackground = False
          TabOrder = 1
          object btnAtualizar: TSpeedButton
            Left = 94
            Top = 0
            Width = 94
            Height = 93
            Align = alLeft
            Caption = 'Atualizar'
            ImageIndex = 1
            Flat = True
            Layout = blGlyphTop
            ExplicitLeft = 0
            ExplicitHeight = 94
          end
          object btnCadastro: TSpeedButton
            Left = 0
            Top = 0
            Width = 94
            Height = 93
            Align = alLeft
            Caption = 'Novo'
            ImageIndex = 0
            Flat = True
            Layout = blGlyphTop
            OnClick = btnCadastroClick
            ExplicitTop = 4
          end
        end
      end
    end
    object pnlCenter: TPanel
      Left = 0
      Top = 141
      Width = 1106
      Height = 482
      Align = alClient
      BevelOuter = bvNone
      Padding.Left = 150
      Padding.Top = 10
      Padding.Right = 150
      Padding.Bottom = 50
      ParentBackground = False
      TabOrder = 1
      object pnlBodyData: TPanel
        Left = 480
        Top = 10
        Width = 476
        Height = 422
        Align = alClient
        BevelOuter = bvNone
        ParentBackground = False
        TabOrder = 0
        object DBGrid1: TDBGrid
          Left = 332
          Top = 49
          Width = 144
          Height = 332
          Align = alRight
          DataSource = DataSource1
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          Options = [dgTitles, dgIndicator, dgRowLines, dgTabs, dgConfirmDelete, dgCancelOnExit, dgTitleClick, dgTitleHotTrack]
          ParentFont = False
          TabOrder = 0
          TitleFont.Charset = DEFAULT_CHARSET
          TitleFont.Color = clWindowText
          TitleFont.Height = -13
          TitleFont.Name = 'Tahoma'
          TitleFont.Style = []
          OnDblClick = DBGrid1DblClick
          OnTitleClick = DBGrid1TitleClick
        end
        object pnlBodyPesquisa: TPanel
          Left = 0
          Top = 0
          Width = 476
          Height = 49
          Align = alTop
          BevelOuter = bvNone
          Padding.Right = 15
          Padding.Bottom = 5
          TabOrder = 1
          object pnlPesquisa: TPanel
            Left = 187
            Top = 0
            Width = 274
            Height = 44
            Align = alRight
            BevelOuter = bvNone
            TabOrder = 0
            object lblPesquisa: TLabel
              Left = 0
              Top = 0
              Width = 274
              Height = 16
              Align = alTop
              Caption = 'Pesquisa'
              ExplicitWidth = 50
            end
            object edtPesquisa: TEdit
              Left = 0
              Top = 16
              Width = 274
              Height = 22
              Align = alTop
              BorderStyle = bsNone
              CharCase = ecUpperCase
              Color = clBtnFace
              TabOrder = 0
              OnKeyPress = edtPesquisaKeyPress
            end
            object pnlLinhaPesquisa: TPanel
              Left = 0
              Top = 38
              Width = 274
              Height = 2
              Align = alTop
              TabOrder = 1
            end
          end
        end
        object pnlBotoesPagina: TPanel
          Left = 0
          Top = 381
          Width = 476
          Height = 41
          Align = alBottom
          BevelOuter = bvNone
          TabOrder = 2
          object btnVoltarPagina: TSpeedButton
            Left = 338
            Top = 0
            Width = 50
            Height = 41
            Align = alRight
            ImageIndex = 7
            Flat = True
            OnClick = btnVoltarPaginaClick
            ExplicitLeft = 260
            ExplicitTop = 6
          end
          object btnProximaPagina: TSpeedButton
            Left = 426
            Top = 0
            Width = 50
            Height = 41
            Align = alRight
            ImageIndex = 6
            Flat = True
            OnClick = btnProximaPaginaClick
            ExplicitLeft = 353
          end
          object lblNumeroPagina: TLabel
            Left = 388
            Top = 0
            Width = 38
            Height = 41
            Align = alRight
            Caption = 'P'#225'gina'
            Layout = tlCenter
            ExplicitHeight = 16
          end
        end
      end
      object pnlCadastro: TPanel
        Left = 150
        Top = 10
        Width = 330
        Height = 422
        Align = alLeft
        BevelOuter = bvNone
        TabOrder = 1
        object pnlAcoes: TPanel
          Left = 0
          Top = 357
          Width = 330
          Height = 65
          Align = alBottom
          BevelOuter = bvNone
          TabOrder = 0
          object btFechar: TSpeedButton
            Left = 137
            Top = 0
            Width = 65
            Height = 65
            Align = alRight
            Caption = 'Fechar'
            ImageIndex = 5
            Flat = True
            Layout = blGlyphTop
            OnClick = btFecharClick
            ExplicitLeft = -6
          end
          object btnSalvar: TSpeedButton
            Left = 266
            Top = 0
            Width = 64
            Height = 65
            Align = alRight
            Caption = 'Salvar'
            ImageIndex = 3
            Flat = True
            Layout = blGlyphTop
            OnClick = btnSalvarClick
            ExplicitLeft = 71
          end
          object btExcluir: TSpeedButton
            Left = 202
            Top = 0
            Width = 64
            Height = 65
            Align = alRight
            Caption = 'Excluir'
            ImageIndex = 4
            Flat = True
            Layout = blGlyphTop
            OnClick = btExcluirClick
            ExplicitLeft = 71
          end
        end
      end
    end
  end
  object DataSource1: TDataSource
    Left = 1016
    Top = 157
  end
end
